var quote =[
  "I love you the more in that I believe you had liked me for my own sake and for nothing else.",
  "But man is not made for defeat. A man can be destroyed but not defeated.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "There is nothing permanent except change.",
  "You cannot shake hands with a clenched fist.",
  "Let us sacrifice our today so that our children can have a better tomorrow.",
  "It is better to be feared than loved, if you cannot be both.",
  "The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do. You can act to change and control your life; and the procedure, the process is its own reward.",
  "Do not mind anything that anyone tells you about anyone else. Judge everyone and everything for yourself.",
  "Learning never exhausts the mind.",
  "There is no charm equal to tenderness of heart.",
  "All that we see or seem is but a dream within a dream.",
  "Lord, make me an instrument of thy peace. Where there is hatred, let me sow love.",
  "If you cannot do great things, do small things in a great way.",
  "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak.",
  "Independence is happiness.",
  "The supreme art of war is to subdue the enemy without fighting.",
  "Keep your face always toward the sunshine - and shadows will fall behind you.",
  "Being entirely honest with oneself is a good exercise.",
  "Happiness can exist only in acceptance.",
  "Love has no age, no limit; and no death.",
  "You can't blame gravity for falling in love.",
  "There is only one corner of the universe you can be certain of improving, and that's your own self.",
  "Honesty is the first chapter in the book of wisdom.",
  "The journey of a thousand miles begins with one step.",
  "Whoever is happy will make others happy too.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "There is nothing on this earth more to be prized than true friendship.",
  "A leader is one who knows the way, goes the way, and shows the way.",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
  "There is only one happiness in this life, to love and be loved.",
  "If opportunity doesn't knock, build a door.",
  "The secret of getting ahead is getting started.",
  "Let us be grateful to people who make us happy, they are the charming gardeners who make our souls blossom.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Wise men speak because they have something to say; Fools because they have to say something.",
  "The World is my country, all mankind are my brethren, and to do good is my religion."

];
function newQuote(){
var randomnumber = Math.floor(Math.random()*(quote.length));
document.getElementById('randomquote').innerHTML =quote[randomnumber]
};
